modLoader="javafml"
loaderVersion="[47,)"
#issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="igrobotics"
    version="${file.jarVersion}"
    displayName="Robotics"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" # Homepage
    logoFile="logo.png" #optional
    authors="Renora Io"
    credits="A huge thanks to the Forge team for making modding so accessible to everyone"
    description=''''''

[[dependencies.igrobotics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    side="BOTH"
[[dependencies.igrobotics]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    side="BOTH"
[[dependencies.igrobotics]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.0,)"
    side="BOTH"
[[dependencies.igrobotics]]
    modId="computercraft"
    mandatory=false
    versionRange="[1.110.0,)"
    ordering="NONE"
    side="BOTH"