modLoader="javafml"
loaderVersion="${loader_version}"
#issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="norabotics"
    version="${version}"
    displayName="Robotics"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" # Homepage
    logoFile="logo.png" #optional
    authors="Renora Io"
    credits="A huge thanks to the Forge team for making modding so accessible to everyone"
    description='''
    Robotics adds programmable and customizable robots to Minecraft.
    '''

[[dependencies.norabotics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    side="BOTH"
[[dependencies.norabotics]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    side="BOTH"
[[dependencies.norabotics]]
    modId="geckolib"
    mandatory=true
    versionRange="${geckolib_version}"
    side="BOTH"
[[dependencies.norabotics]]
    modId="computercraft"
    mandatory=false
    versionRange="${cct_version}"
    ordering="NONE"
    side="BOTH"